version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark master port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_OPTS="-Dspark.deploy.defaultCores=3"
    networks:
      - spark_network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    ports:
      - "8081:8081"
      - "17000:17000"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=6g
      - SPARK_WORKER_CORES=3
      - SPARK_DAEMON_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_PORT=17000
      # 수정된 Worker 옵션 설정
      - SPARK_WORKER_CLEANUP_ENABLED=true
      - SPARK_WORKER_CLEANUP_INTERVAL=1800
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - spark_network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    ports:
      - "8082:8081"
      - "17001:17000"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=6g
      - SPARK_WORKER_CORES=3
      - SPARK_DAEMON_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_PORT=17000
      # 수정된 Worker 옵션 설정
      - SPARK_WORKER_CLEANUP_ENABLED=true
      - SPARK_WORKER_CLEANUP_INTERVAL=1800
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - spark_network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G

  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    ports:
      - "8083:8081"
      - "17002:17000"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=6g
      - SPARK_WORKER_CORES=3
      - SPARK_DAEMON_MEMORY=1g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_PORT=17000
      # 수정된 Worker 옵션 설정
      - SPARK_WORKER_CLEANUP_ENABLED=true
      - SPARK_WORKER_CLEANUP_INTERVAL=1800
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - spark_network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - spark_network
    deploy:
      resources:
        limits:
          memory: 2G

  python-app:
    image: session_2-python-app
    container_name: python-app
    working_dir: /app
    volumes:
      - ./app/src:/app/src
      - ./app/tests:/app/tests
      - ./app/scripts:/app/scripts
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    command: ["python", "-m", "main"]
    depends_on:
      - spark-master
      - mongodb
    networks:
      - spark_network
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  spark_network:
    name: spark_network
    driver: bridge